demo:
    environment: prod
    hosts:
        - https://www.example1.com
        - https://www.example2.com
test: hey

spring:
    env: dev
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
        default: dev